name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gunicorn_container/
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t gunicorn_img:$(date +%s) .
    - name: Run and test the image
      run: |
         docker run -d -p 5000:5000 --name gunicorn gunicorn_img:$(date +%s)
         pip3 install -r requirements.txt #prerequencies to run the tests
         python initial_test.py
