name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gunicorn_container/
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gunicorn_img
    - name: Run and test the image
      run: |
         docker run -d -p 5000:5000 --name gunicorn gunicorn_img
         pip3 install -r requirements.txt #prerequencies to run the tests
         python initial_test.py
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: push to dockerhub 
      run: |
         docker images
         docker push romanoo/gunicorn_img:latest
